### ISSUE TITLE
Example toolbar for embed image, video 

### ISSUE THREAD

**Issue by huynhtranvuquocphong** [romainleduc/draft-js-wysiwyg#296]
Hi team,
Do you have source code example for image, video in toolbar?
Please send it to me.
Thanks you!

**Comment by romainleduc** [comment]
Support for youtube, vimeo etc links is now fully supported in version 1.2.1.

You can find examples on these links
https://github.com/romainleduc/draft-js-wysiwyg/tree/master/examples/embedded-link)
https://draft-js-wysiwyg.com/components/button

Hope this helps you :)
