### ISSUE TITLE
Bug with add link

### ISSUE THREAD

**Issue by ghilaslinz** [romainleduc/draft-js-wysiwyg#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I have a small bug with link in Draft js.
When the user creates a link in a different line than the first line. The link is created in the line where the cursor is located **AND IN THE FIRST LINE.**

This a small video that shows the bug :
https://www.loom.com/share/98643cc9e83746198551b59d2f4daa53

### Expected Behavior

I would like that the link will be added only where the cursor is located.

### Steps to reproduce the Behavior

This is the code :  
https://codesandbox.io/s/react-playground-forked-4zkxx?file=/MainPage.js

### Version

1.14.7

### On which browser / OS are you affected by this issue ?

Firefox, Chrome, Safari

@romainleduc

**Comment by romainleduc** [comment]
Hello @ghilaslinz,
Sorry but the example doesn't seem to use my library.
You will need to see directly with the maintainer of [react-draft-wysiwyg](https://github.com/jpuri/react-draft-wysiwyg), like you did [here](https://github.com/jpuri/react-draft-wysiwyg/issues/1208) :)
